spring:
  data:
    mongodb:
      host: 192.168.1.48
      port: 27017
      database: prueba
      username: arbiel
      password: '310391'
      authentication-database: prueba

server:
  port : 8081